# Generated by Django 5.1.5 on 2025-02-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0003_alter_player_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='yearGraduation',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
    ]
