# Generated by Django 5.1.5 on 2025-02-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0004_player_yeargraduation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='icon',
            field=models.ImageField(default='images/default_icon.jpg', upload_to='icons/'),
        ),
    ]
