# Generated by Django 5.1.5 on 2025-02-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0005_alter_player_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='icon',
            field=models.ImageField(default='icons/default_icon.png', upload_to='icons/'),
        ),
    ]
