# Generated by Django 5.1.5 on 2025-02-03 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0006_alter_player_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='yearGraduation',
        ),
        migrations.AddField(
            model_name='player',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2002, 4, 23, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='isGraduated',
            field=models.BooleanField(default=False),
        ),
    ]
