# Generated by Django 5.1.5 on 2025-02-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0007_remove_player_yeargraduation_player_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
