# Generated by Django 5.1.5 on 2025-02-16 01:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0008_player_role_alter_player_name_alter_player_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.IntegerField()),
                ('date', models.DateField()),
                ('startTime', models.DateTimeField(null=True)),
                ('endTime', models.DateTimeField(null=True)),
                ('playTime', models.TimeField(null=True)),
                ('dice2', models.IntegerField(default=0)),
                ('dice3', models.IntegerField(default=0)),
                ('dice4', models.IntegerField(default=0)),
                ('dice5', models.IntegerField(default=0)),
                ('dice6', models.IntegerField(default=0)),
                ('dice7', models.IntegerField(default=0)),
                ('dice8', models.IntegerField(default=0)),
                ('dice9', models.IntegerField(default=0)),
                ('dice10', models.IntegerField(default=0)),
                ('dice11', models.IntegerField(default=0)),
                ('dice12', models.IntegerField(default=0)),
                ('recentDice1', models.IntegerField(null=True)),
                ('recentDice2', models.IntegerField(null=True)),
                ('recentDice3', models.IntegerField(null=True)),
                ('recentDice4', models.IntegerField(null=True)),
                ('recentDice5', models.IntegerField(null=True)),
                ('recentDice6', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='PersonalResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('win', models.BooleanField(default=False)),
                ('color', models.IntegerField()),
                ('dice2', models.IntegerField(default=0)),
                ('dice3', models.IntegerField(default=0)),
                ('dice4', models.IntegerField(default=0)),
                ('dice5', models.IntegerField(default=0)),
                ('dice6', models.IntegerField(default=0)),
                ('dice7', models.IntegerField(default=0)),
                ('dice8', models.IntegerField(default=0)),
                ('dice9', models.IntegerField(default=0)),
                ('dice10', models.IntegerField(default=0)),
                ('dice11', models.IntegerField(default=0)),
                ('dice12', models.IntegerField(default=0)),
                ('land', models.IntegerField(default=0)),
                ('city', models.IntegerField(default=0)),
                ('card', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('longestRoad', models.BooleanField(default=False)),
                ('largestArmy', models.BooleanField(default=False)),
                ('halfPoint', models.IntegerField(default=0)),
                ('yellowFriend', models.BooleanField(default=False)),
                ('greenFriend', models.BooleanField(default=False)),
                ('readFriend', models.BooleanField(default=False)),
                ('blueFriend', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catan.gameresult')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catan.player')),
            ],
        ),
    ]
