# Generated by Django 5.1.5 on 2025-02-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0009_gameresult_alter_player_password_personalresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalresult',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
