# Generated by Django 5.1.5 on 2025-03-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0010_personalresult_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameresult',
            name='turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='title',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='personalresult',
            name='color',
            field=models.CharField(max_length=8),
        ),
    ]
