# Generated by Django 5.1.5 on 2025-03-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0011_gameresult_turn_alter_gameresult_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameresult',
            name='turn',
            field=models.IntegerField(default=1),
        ),
    ]
