# Generated by Django 5.1.5 on 2025-03-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0012_alter_gameresult_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalresult',
            name='road',
            field=models.IntegerField(default=0),
        ),
    ]
