# Generated by Django 5.1.5 on 2025-03-16 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catan', '0013_personalresult_road'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalresult',
            name='road',
        ),
    ]
